# Generated by Django 5.1.6 on 2025-02-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_doctorreview_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
