GET http://127.0.0.1:8000/accounts/api/auth/profile/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5OTc5MTc1LCJpYXQiOjE3Mzk5Nzg4NzUsImp0aSI6Ijk5NTFmMTNiODljZTQ0MDc4ZjViZGI1YWJmMDI4OWY3IiwidXNlcl9pZCI6MzV9.wVtFZ6Z4AsqqVlrmDLYmFMVvN_uwC8eMqO0ghzsJKwI
accept: application/json


