# Generated by Django 5.1.6 on 2025-02-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
