# Generated by Django 5.1.6 on 2025-02-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0010_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
