# Generated by Django 5.1.6 on 2025-02-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0011_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
